# Демо: виртуальные часы идут с 28.10.2025 03:00

services:
  ingest:
    environment:
      CLOCK_START: "2025-10-28T03:00:00"
      CLOCK_END: "2025-11-28T23:00:00"
      CLOCK_SPEED: "750"
      INGEST_POLL_SEC: "5"

  ml-worker:
    environment:
      CLOCK_START: "2025-10-28T03:00:00"
      CLOCK_SPEED: "750"
      CLOCK_END: "2025-11-28T23:00:00"
      MIN_RERUN_MINUTES: "2"
      WORKER_POLL_SEC: "10"
